### ISSUE TITLE
Нестабильная работа тестов

### ISSUE THREAD

**Issue by burenkov-anton** [hexlet-basics/exercises-csharp#21]
Тесты то падают, то проходят, даже если код не менялся. В независимости от упражнения, во - всяком случае однозначно воспроизводится на упражнениях с выводом в консоль.
Вывод или такой
![Unstable2](https://user-images.githubusercontent.com/11513918/145663937-0ddecc2a-70e8-4474-9b79-fae67a144358.png)

или такой

![Unstable](https://user-images.githubusercontent.com/11513918/145663939-4d18ea46-c1b2-4a50-9a6c-c2aa53d4df92.png)

**Comment by corsicanec82** [comment]
Тут была проблема с дилтельным запуском тестов.
Заменили использование dotnet на mono, что позволило ускорить выполнение тестов.
https://github.com/hexlet-basics/exercises-csharp/pull/22
Теперь всё работает корректно.
