### ISSUE TITLE
Любое решение в тренажере принимается, даже неправльное

### ISSUE THREAD

**Issue by Jeka-Vasiliev** [hexlet-basics/exercises-csharp#45]
Можно написать хоть:
```cs
throw new Exception("fail");
```

Результатом будет "Ура! Всё получилось!"

**Comment by corsicanec82** [comment]
Поправил этот баг
https://github.com/hexlet-basics/exercises-csharp/commit/cd2747d98538b4fbe581745d85a9f22a4ab1aaff
Как выяснилось есть нюанс при использовании либы PowerAssert.
Если совершить ошибку в файле с решением, даже синтаксическую, и использовать решение в вызове:

```
PAssert.IsTrue(() => App.NormalizeUrl("yandex.ru") == "https://yandex.ru");
```

то при этом ошибки выводятся в консоль, если они есть, но код завершения 0.

Если же работать с кодом решения снаружи, а в вызов передавать переменную содержащую результат, то всё ок. Например:

```
var actual1 = App.NormalizeUrl("yandex.ru");
PAssert.IsTrue(() => actual1 == "https://yandex.ru");
```
