### ISSUE TITLE
Тесты пропускают некорректный код

### ISSUE THREAD

**Issue by zhabinka** [hexlet-basics/exercises-csharp#60]
Решение проходит даже с явными ошибками. Например, здесь –  https://ru.code-basics.com/languages/csharp/lessons/if

**Comment by dzencot** [comment]
https://ru.code-basics.com/languages/csharp/lessons/escape-characters#editor - со строками тоже самое

**Comment by corsicanec82** [comment]
Спасибо ребята.
Поведение тестов пофиксил. Сейчас всё должно отрабатывать именно так как ожидается.
Данный ишью закрываю.

**Comment by zhabinka** [comment]
https://github.com/hexlet-basics/exercises-csharp/commit/96f169893fd1c1559267d9b6cb47bc1871f2a160#diff-0c00bf2bed639143e757627eb220b3ab66e3a426abfb1a51b128af4cc278f2efR6-R7
 Коммент можно удалить.
